### ISSUE TITLE
"Tracker Suppoert is not available. Please Install OpenXRTrackerProfile"

### ISSUE THREAD

**Issue by Killertamagotchi** [nicoco007/BeatSaber-ExtraOpenXRFeatures#1]
I only get the message when setting up FBT.
![Screenshot 2024-07-09 20-05-51](https://github.com/nicoco007/BeatSaber-ExtraOpenXRFeatures/assets/7459253/56bcab07-22ac-4d55-9889-347266c1005d)
I use HTC Vive Tracker 3.0 and according to the instructions you don't have to set anything extra than what you already do (i.e. assign what the respective tracker is for)
maybe I'm missing something but I've copied the necessary files into the folders

**Comment by nicoco007** [comment]
Did you install OpenXR Tracker Profiles and its dependencies (OpenXR Feature Manager) from [this repo's Releases page](https://github.com/nicoco007/BeatSaber-ExtraOpenXRFeatures/releases)?

**Comment by nicoco007** [comment]
I'll be closing this issue within the next few days if I don't hear back.

**Comment by Killertamagotchi** [comment]
oh I didn't even notice that there was a reply to that. But I saw that there were still files missing that I had overlooked downloading 😅
